export interface Project {
    slug: string;
    title: string;
    shortDescription: string;
    description: string;
    techStack: string[];
    image: string;
    category: "Hackathon" | "Freelance" | "Internal";
    outcome?: string;
  }
  
  export const projects: Project[] = [
    {
      slug: "ai-code-generation-platform",
      title: "AI Code Generation Platform",
      shortDescription: "Multi-model platform for optimized code generation.",
      description:
        "A comparative AI platform that evaluates and optimizes code generated by multiple LLMs using validation, testing, and refactoring pipelines.",
      techStack: ["Next.js", "Python", "LLMs", "Docker"],
      image: "/projects/codegen.png",
      category: "Internal",
      outcome: "Used as a research and experimentation platform."
    },
    {
      slug: "smart-hackathon-solution",
      title: "Smart Hackathon Solution",
      shortDescription: "End-to-end AI-driven system built under time pressure.",
      description:
        "Built during a national-level hackathon focusing on scalability, rapid prototyping, and real-world usability.",
      techStack: ["React", "Node.js", "AI APIs"],
      image: "/projects/hackathon.png",
      category: "Hackathon",
      outcome: "Won top positions among competing teams."
    }
  ];
  